addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"      % "1.4.2")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"  % "0.9.0")
addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.5.3")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"       % "2.2.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.4.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.12")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"   % "0.9.23")
