addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"      % "1.3.5")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"  % "0.9.0")
addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.5.2")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"       % "2.1.5")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.3.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.10")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"   % "0.9.15")
